const Prodata = [
    {
      id: 1,
      name: "Sennheiser - HD 660S2",
      price: 29990,
      rating: 4.5,
      image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-660S2-02.jpg?v=1678449682&width=1000",
      image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-660S2-01.jpg?v=1678449682&width=1000",
      category: 'headphones',
      img5: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-660S2-17.jpg?v=1719229582&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-660S2-16.jpg?v=1719229582&width=600",
      img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-660S2-14.jpg?v=1719229582&width=600",
      bname: "SENNHEISER",
      pname: "HD 660 S2",
      des: "The new, high-end Sennheiser HD 660S2 headphone outperforms the iconic HD 660S's excellent performance. Sennheiser is attempting to expand its product line with the HD 660S2, designed specifically for the most demanding listeners. An eye-catching new matte black design is featured on the Sennheiser HD 660S2. It has a classically exquisite appearance with some modern influences.",
      fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-HD-660S2-graph.png?v=1729057570",
      drivers: "38mm Dynamic Driver",
      connectors: "4.4mm (Balanced)\n6.35mm (Single-Ended)\n3.5mm (Single-Ended)",
      sensi: "",
      fres: "8 – 41,500 Hz",
      impedence: "300 Ω",
      thd: "<0.04% (1kHz, 94dB)",  
      weight: "260g",  
      cable: "3m detachable (4.4mm/6.35mm/3.5mm)",  
      inTheBox: "Headphones, 3m cable, 6.35mm adapter, storage pouch"  
    },
    {
      id: 2,
      name: "Sennheiser - HD 800 S",
      price: 134990,
      rating: 4.2,
      image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-800-S-1160-1160-1.jpg?v=1593668952&width=1000",
      image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-800-S-1160-1160-3.jpg?v=1593668952&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-800-S-1160-1160-2.jpg?v=1593668952&width=600",
      img4: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-HD-800-S-1180-450-1.jpg?v=1593663988",
      img5: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-800-S-1160-1160-4.jpg?v=1657361721&width=600",
      bname: "SENNHEISER",
      pname: "HD 800 S",
      des: "The Sennheiser HD 800s sport an open, circum-aural dynamic stereo headphone design that makes you feel directly connected to the music. Music emerges from silence and sounds so profound that would travel into a soundstage of amazement. Soundstage refers to being able to sense the spatial surroundings of a recording.",
      fr: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD800s-Gallery.jpg?v=1657361721&width=600",
      drivers: "Dynamic Open",
      connectors: "6.35 mm/ 4.4 mm\nXLR-4 (optional)",
      sensi: "102 dB @ 1 kHz",
      fres: "4 – 51000 Hz (- 10 dB)",
      impedence: "300 Ohms",
      thd: "<0.02% (1kHz, 1Vrms)",  
      weight: "330g",  
      cable: "3m detachable (6.35mm/4.4mm)",  
      inTheBox: "Headphones, 6.35mm cable, XLR-4 cable (optional), storage box"  
    },
    {
      id: 3,
      name: "Sennheiser - HD 820",
      price: 164990,
      rating: 4.7,
      image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-820-1160-1160-1.jpg?v=1593677179&width=1000",
      image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-820-1160-1160-3.jpg?v=1593677197&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD-820-1160-1160-2.jpg?v=1593677188&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/products/sennheiser-hd-820-headphone-zone-4232625455167.jpg?v=1593677206&width=600",
      img5: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-HD-820-1180-450-12.jpg?v=1593674529",
      bname: "SENNHEISER",
      pname: "HD 820",
      des: "The Sennheiser HD 820s sport a closed, circum-aural dynamic stereo headphone design that makes you feel directly connected to the music. Music emerges from silence and sounds so profound that would travel into a soundstage of amazement.",
      fr: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-HD820-Gallery.jpg?v=1657354082&width=1000",
      drivers: "dynamic, closed",
      connectors: "6.35 mm / 4.4 mm\nXLR-4 (optional)",
      sensi: "103 dB at 1 kHz, 1V",
      fres: "12 - 43800 Hz (-3 dB)\n6 - 48000 Hz (-10 dB)",
      impedence: "300 Ohms",
      thd: "<0.03% (1kHz, 1Vrms)",  
      weight: "360g",  
      cable: "3m detachable (6.35mm/4.4mm)",  
      inTheBox: "Headphones, 6.35mm cable, XLR-4 cable (optional), storage box"  
    },
    {
      id: 4,
      name: "Focal - Stellia",
      price: 184999,
      rating: 4.8,
      image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-02.jpg?v=1726573473&width=1000",
      image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-01.jpg?v=1726573460&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-03.jpg?v=1726573485&width=1000",
      img5: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-09.jpg?v=1726573571&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-04.jpg?v=1726573497&width=600",
      bname: "FOCAL",
      pname: "Stellia",
      des: "Focal has continued to push its boundaries over the years. Its ultimate mission - Continuous innovation through a unique approach aimed at constantly exceeding the limits of acoustics and sound engineering is a testament to Hi-Fidelity Sound. Focal's brand-new Stellia Closed-back circum-aural headphone is the prime example of cutting-edge technology, innovation, and exceptional aesthetics.",
      fr: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Stellia-08.jpg?v=1726573559&width=600",
      drivers: "1.6\" (40mm) Pure Beryllium \"M\" Shape Dome",
      connectors: "3.5mm (Single-Ended)6.35mm (Single-Ended)4-Pin XLR (Balanced)",
      sensi: "106dB SPL / 1mW @ 1kHz",
      fres: "5Hz – 40kHz",
      impedence: "35 Ohms",
      thd: "<0.1% (1kHz, 100dB SPL)",  
      weight: "435g",  
      cable: "1.2m (3.5mm) + 3m (XLR balanced)",  
      inTheBox: "Headphones, 3.5mm/6.35mm/XLR cables, travel case"  
    },
    {
      id: 5,
      name: "Focal - Azurys",
      price: 36999,
      rating: 4.7,
      image: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Focal-Azurys-02.jpg?v=1715161192&width=1000",
      image1: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Focal-Azurys-01.jpg?v=1715161192&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Focal-Azurys-03.jpg?v=1720078055&width=600",
      img5: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Focal-Azurys-014.jpg?v=1720078055&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Focal-Azurys-04.jpg?v=1720078055&width=600",
      bname: "FOCAL",
      pname: "Azurys",
      des: "Azurys are Focal’s new passive closed-back headphones, designed for enjoying music on the go or at home. The all-new Focal Azurys feature 40mm Aluminium/Magnesium 'M' dome drivers, designed and engineered in France. The Focal Azurys are the perfect blend of premium materials, innovative technology and a classic design that sets it apart in the world of high-quality audio.",
      fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-zone-Focal-Azurys-Graph-new.png?v=1738317981",
      drivers: "15/8'' (40mm) Aluminium/ Magnesium ‘M’-Shaped Dome",
      connectors: "3.5mm (Single-Ended)\n6.35mm (Single-Ended)",
      sensi: "100dB SPL / 1mW @ 1kHz",
      fres: "15 Hz - 22 kHz",
      impedence: "26 Ω",
      thd: "<0.2% (1kHz, 100dB SPL)",  
      weight: "320g",  
      cable: "1.5m detachable (3.5mm/6.35mm)",  
      inTheBox: "Headphones, 3.5mm cable, 6.35mm adapter, carrying pouch"  
    },
    {
      id: 6,
      name: "FiiO - FT1",
      price: 14999,
      rating: 4.7,
      image: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FiiO-FT1-02.jpg?v=1724142980&width=1000",
      image1: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FiiO-FT1-04.jpg?v=1724142980&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FiiO-FT1-015.jpg?v=1724142980&width=600",
      img5: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FiiO-FT1-012.jpg?v=1724142981&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FiiO-FT1-07.jpg?v=1724142980&width=600",
      bname: "FIIO",
      pname: "FT1",
      des: "The FT1 is FiiO's latest offering in full-sized dynamic driver headphones, featuring a 60mm driver with a nano wood fibre composite diaphragm for powerful, low-distortion sound and exceptional clarity. Engineered for an ultra-wide frequency response of 10Hz to 40kHz, the FT1 showcases FiiO's dedication to innovation. Its premium construction includes an adaptive 3-axis headband for optimal comfort.",
      fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-zone-FiiO-FT1-graph.png?v=1724149256",
      drivers: "60mm Dynamic Driver",
      connectors: "Dual 3.5mm TRS",
      sensi: "98dB/mW@1kHz\n113dB/Vrms@1kHz",
      fres: "10Hz-40kHz",
      impedence: "32 Ω",
      thd: "<0.2% (1kHz)",  
      weight: "350g",  
      cable: "1.8m detachable (dual 3.5mm)",  
      inTheBox: "Headphones, cable, 6.35mm adapter, storage bag"  
    },
    {
      id: 7,
      name: "Sennheiser - HD 620S",
      price: 29990,
      rating: 4.7,
      image: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-HD-620S-03.jpg?v=1717157896&width=1000",
      image1: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-HD-620S-01.jpg?v=1717157897&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-HD-620S-02.jpg?v=1717157896&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-HD-620S-015.jpg?v=1717158125&width=600",
      img5: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-HD-620S-06.jpg?v=1717158125&width=600",
      bname: "SENNHEISER",
      pname: "HD 620S",
      des: "The Sennheiser HD 620S closed-back headphones redefine the boundaries of private listening, offering audio enthusiasts a blend of distraction-free immersion with natural and airy sound. It features advanced 42 mm angled transducers and ultra-light 150-ohm aluminium voice coils for expansive and speaker-like imaging.",
      fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-HD-620S-Graph.png?v=1719817732",
      drivers: "42 mm Dynamic with 38 mm Duofol diaphragm",
      connectors: "3.5mm (Single-Ended)\n6.35mm (Single-Ended)",
      sensi: "110 dB (1 kHz / 1 Vrms)",
      fres: "6 Hz - 30 kHz",
      impedence: "150 Ohm",
      thd: "<0.1% (94dB SPL)",  
      weight: "220g",  
      cable: "1.8m detachable (3.5mm/6.35mm)",  
      inTheBox: "Headphones, cable, 6.35mm adapter, user manual"  
    },
    {
      id: 8,
      name: "Focal - Bathys",
      price: 69999,
      rating: 4.7,
      image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-Bathys-New-4.jpg?v=1694759796&width=1000",
      image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-bathys-New-010.jpg?v=1694759796&width=1000",
      category: 'headphones',
      img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-bathys-New-09.jpg?v=1694759796&width=600",
      img4: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-bathys-New-023.jpg?v=1694759796&width=600",
      img5: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Focal-bathys-New-026.jpg?v=1694759796&width=600",
      bname: "FOCAL",
      pname: "Bathys",
      des: "Focal is proudly introducing their first-ever Active Noise Cancelling wireless headphones - the Bathys. Bathys is Focals' first high-end wireless headphone that promises to deliver exceptional performance wirelessly with Bluetooth support.",
      fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Focal-Bathys-Graph.png?v=1720871648",
      drivers: "40mm Aluminium-Magnesium",
      connectors: "Bluetooth® / Jack 3.5mm / USB-C®",
      sensi: "",
      fres: "15Hz To 22kHz",
      impedence: "",
      thd: "<0.1% (ANC off)",  
      weight: "350g",  
      cable: "1.2m USB-C (for wired mode)",  
      inTheBox: "Headphones, USB-C cable, 3.5mm cable, travel case"  
    },
    {
        id: 9,
        name: "Kinera - Relentless",
        price: 10999, 
        rating: 4.6,
        image: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Kinera-Celest-Relentless-014.jpg?v=1718629379&width=1000  ",
        image1: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Kinera-Celest-Relentless-016.jpg?v=1718453301&width=1000",
        category: "iems",
        img5: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Kinera-Celest-Relentless-Gallery-102.jpg?v=1738736809&width=1000 ",
        img4: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Kinera-Celest-Relentless-01.jpg?v=1718629379&width=1000  ",
        img3: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Kinera-Celest-Relentless-010.jpg?v=1718453313&width=1000 ",
        bname: "KINERA",
        pname: "Relentless",
        des: "The Kinera Relentless combines 6 balanced armatures and 1 dynamic driver in a hybrid setup, delivering a wide frequency response (10Hz–40kHz) with exceptional clarity and bass impact. Its 'Acoustic Maze' internal design enhances soundstage, while the resin shells and intricate faceplates offer a premium aesthetic. Ideal for audiophiles seeking technical precision and immersive staging.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Kinera-Celest-Relentless-graph01.png?v=1718630565  ",
        drivers: "6BA + 1DD Hybrid",
        connectors: "2-pin (Detachable)",
        sensi: "108dB/mW",
        fres: "10Hz – 40kHz",
        impedence: "18Ω",
        thd: "<0.5% (1kHz)",  
        weight: "25g (approx.)",  
        cable: "High-purity silver-plated copper",  
        inTheBox: "IEMs, cable, ear tips, carrying case"  
      },
      {
        id: 10,
        name: "Simgot - EA2000",
        price: 28999, 
        rating: 4.4,
        image1: "  https://conceptkart.com/cdn/shop/files/Concept-Kart-Simgot-EA2000-IEM-Slvr-1_1.jpg?v=1706529053&width=600  ",
        image: "   https://m.media-amazon.com/images/I/51unG2doqbL._AC_SX679_.jpg ",
        category: "iems",
        img5: "   https://conceptkart.com/cdn/shop/files/Concept-Kart-Simgot-EA2000-IEM-Slvr-2_6_900x.jpg?v=1706529297 ",
        img4: "  https://conceptkart.com/cdn/shop/files/Concept-Kart-Simgot-EA2000-IEM-Slvr-1_3.jpg?v=1706529054&width=600  ",
        img3: "  https://conceptkart.com/cdn/shop/files/Concept-Kart-Simgot-EA2000-IEM-Slvr-1_2.jpg?v=1706529054&width=600  ",
        bname: "SIMGOT",
        pname: "EA2000",
        des: "The Simgot EA2000 features a dual-magnet dynamic driver for tight, controlled bass and extended treble. Its brass sound chamber optimizes resonance, while swappable acoustic nozzles let you toggle between balanced and treble-focused signatures. With 122dB/Vrms sensitivity and a 10Hz–40kHz range, it's a versatile pick for detail lovers.",
        fr: " https://www.linsoul.com/cdn/shop/products/10_c4ff8d8b-8f44-4a5f-9677-d90ab7f7baf6.jpg?v=1677061526&width=713   ",
        drivers: "1DD (Dual-Magnet)",
        connectors: "2-pin (Detachable)",
        sensi: "122dB/Vrms (~100dB/mW)",
        fres: "10Hz – 40kHz",
        impedence: "32Ω",
        thd: "<0.3% (1kHz)",  
        weight: "20g (approx.)",  
        cable: "OFC stock cable",  
        inTheBox: "IEMs, cable, nozzles, ear tips, case",
        needblack : "yes",
      },
      {
        id: 11,
        name: "Thieaudio - Hype 4",
        price: 30000, 
        rating: 4.7,
        image1: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-ThieAudio-Hype-4-Black-01.jpg?v=1707373738&width=1000   ",
        image: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-ThieAudio-Hype-4-Black-19.jpg?v=1707373738&width=1000  ",
        category: "iems",
        img5: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-ThieAudio-Hype-4-Black-03.jpg?v=1707373709&width=1000  ",
        img4: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-ThieAudio-Hype-4-Black-07.jpg?v=1707373709&width=1000   ",
        img3: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-ThieAudio-Hype-4-Black-04.jpg?v=1707373709&width=1000   ",
        bname: "THIEAUDIO",
        pname: "Hype 4",
        des: "The Thieaudio Hype 4 blends 4 balanced armatures with a 10mm dynamic driver for a balanced yet punchy sound. Its semi-headphones design widens the soundstage, while the 4-way crossover ensures seamless driver cohesion. With 112dB/mW sensitivity and 24Ω impedance, it's easy to drive and excels in both vocals and bass.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-AFUL-Performer-8-Graph.png?v=1717401193  ",
        drivers: "4BA + 1DD Hybrid",
        connectors: "2-pin (Detachable)",
        sensi: "112dB/mW",
        fres: "20Hz – 40kHz",
        impedence: "24Ω",
        thd: "<0.2% (1kHz)",  
        weight: "22g (approx.)",  
        cable: "4-core silver-plated copper",  
        inTheBox: "IEMs, cable, ear tips, carrying pouch"  
      },
      {
        id: 12,
        name: "AFUL - Performer 8",
        price: 27999, 
        rating: 4.8,
        image1: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-AFUL-Performer-8-3.5mm-Gallery-Image-06.jpg?v=1717418907&width=1000  ",
        image: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-AFUL-Performer-8-3.5mm-Gallery-04.jpg?v=1717419230&width=1000   ",
        category: "iems",
        img5: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-AFUL-Performer-8-3.5mm-Gallery-Image-07.jpg?v=1717419756&width=1000   ",
        img4: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-AFUL-Performer-8-3.5mm-Gallery-05.jpg?v=1717419250&width=1000 ",
        img3: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-AFUL-Performer8-Gallery-01.jpg?v=1717072165&width=1000  ",
        bname: "AFUL",
        pname: "Performer 8",
        des: "The AFUL Performer 8 packs 8 balanced armatures into a compact shell, tuned with 3D-printed acoustic chambers for precision. Its 4-way crossover and dedicated subwoofer BA deliver deep bass and sparkling highs, while the 122dB/mW sensitivity ensures efficiency. A technical marvel for critical listening.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-AFUL-Performer-8-Graph.png?v=1717401193  ",
        drivers: "8BA",
        connectors: "2-pin (Detachable)",
        sensi: "122dB/mW",
        fres: "20Hz – 40kHz",
        impedence: "16Ω",
        thd: "<0.1% (1kHz)",  
        weight: "24g (approx.)",  
        cable: "4N OFC stock cable",  
        inTheBox: "IEMs, cable, ear tips, storage case"  
      },
      {
        id: 13,
        name: "Moondrop - Solis 2",
        price: 250000, 
        rating: 4.5,
        image1: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Moondrop-Solis2-gallery.jpg?v=1702459936&width=1000  ",
        image: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Moondrop-Solis2-gallery-01.jpg?v=1702461390&width=1000  ",
        category: "iems",
        img5: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Moondrop-Solis2-gallery-07.jpg?v=1702473500&width=1000   ",
        img4: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Moondrop-Solis2-gallery-08.jpg?v=1702473500&width=1000 ",
        img3: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Moondrop-Solis2-gallery-06.jpg?v=1702473494&width=1000 ",
        bname: "MOONDROP",
        pname: "Solis 2",
        des: "The Moondrop Solis 2 features coaxial dual dynamic drivers (one for bass, one for mids/treble) in a sleek design. Its 'Virtual Diffusion Sound Field' tuning creates a holographic soundstage, and the 10Hz–50kHz range ensures ultra-wide frequency reproduction. A unique take on DD-based IEMs.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-AFUL-Performer-8-Graph.png?v=1717401193  ",
        drivers: "2DD (Coaxial)",
        connectors: "2-pin (Detachable)",
        sensi: "120dB/Vrms (~105dB/mW)",
        fres: "10Hz – 50kHz",
        impedence: "32Ω",
        thd: "<0.2% (1kHz)",  
        weight: "18g (approx.)",  
        cable: "5N OFC stock cable",  
        inTheBox: "IEMs, cable, ear tips, carrying case"  
      },
      {
        id: 14,
        name: "64 Audio - U12t",
        price: 159800, 
        rating: 4.9,
        image1: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-64-Audio-U12t-Gallery-101.jpg?v=1742449919&width=1000  ",
        image: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-64-Audio-U12t-Gallery-1001.jpg?v=1742449919&width=1000 ",
        category: "iems",
        img5: "  https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-64-Audio-U12t-09.jpg?v=1742449919&width=1000  ",
        img4: " https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-64-Audio-U12t-10.jpg?v=1742449919&width=1000   ",
        img3: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-64-Audio-U12t-inthebox.jpg?v=1742449919&width=1400  ",
        bname: "64 AUDIO",
        pname: "U12t",
        des: "The 64 Audio U12t is a flagship IEM with 12 balanced armatures and patented APEX technology for reduced ear fatigue. Its tia (tubeless) drivers deliver pristine treble, while the 4-way crossover ensures coherence. With a 10Hz–20kHz range and 108dB/mW sensitivity, it's a reference-grade monitor for professionals.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sony-IER-Z1R-Graph.png?v=1688039351  ",
        drivers: "12BA",
        connectors: "2-pin (Detachable)",
        sensi: "108dB/mW",
        fres: "10Hz – 20kHz",
        impedence: "6Ω (with APEX)",
        thd: "<0.5% (1kHz)",  
        weight: "28g (approx.)",  
        cable: "Premium stock cable",  
        inTheBox: "IEMs, cable, APEX modules, ear tips, pelican case"  
      },
      {
        id: 15,
        name: "Sony - IER-Z1R",
        price: 159990, 
        rating: 4.8,
        image1: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sony-IER-Z1R-01.jpg?v=1688026093&width=1000   ",
        image: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sony-IER-Z1R-02.jpg?v=1688026095&width=1000  ",
        category: "iems",
        img5: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sony-IER-Z1R-09.jpg?v=1688026101&width=1000 ",
        img4: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sony-IER-Z1R-07.jpg?v=1688026101&width=1000  ",
        img3: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sony-IER-Z1R-05.jpg?v=1688026101&width=1000  ",
        bname: "SONY",
        pname: "IER-Z1R",
        des: "The Sony IER-Z1R combines a 5mm dynamic driver, BA, and magnesium-cased super tweeter for an extreme 3Hz–100kHz range. Its zirconium housings isolate noise while the Kimber Kable ensures signal purity. With 103dB/mW sensitivity and 40Ω impedance, it demands power but rewards with unparalleled resolution.",
        fr: " https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sony-IER-Z1R-Graph.png?v=1688039351   ",
        drivers: "1DD + 1BA + 1Super Tweeter",
        connectors: "MMCX (Detachable)",
        sensi: "103dB/mW",
        fres: "3Hz – 100kHz",
        impedence: "40Ω",
        thd: "<0.3% (1kHz)",  
        weight: "30g (approx.)",  
        cable: "Kimber Kable (MMCX)",  
        inTheBox: "IEMs, cable, ear tips, carrying case"  
      },
      {
        id: 16,
        name: "FatFreq - Deuce",
        price: 19800, 
        rating: 4.3,
        image1: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FATfreqXHBB-Deuce-3.5mm-01.jpg?v=1735632565&width=1000  ",
        image: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FATfreqXHBB-Deuce-3.5mm-02.jpg?v=1735632565&width=1000  ",
        category: "iems",
        img5: " https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FATfrequency-X-HBB-Deuce-03.jpg?v=1735650131&width=1000   ",
        img4: "  https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FATfreqXHBB-Deuce-3.5mm-07.jpg?v=1735632565&width=1000  ",
        img3: "   https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-FATfreqXHBB-Deuce-3.5mm-013.jpg?v=1735632565&width=1000 ",
        bname: "FATFREQ",
        pname: "Deuce",
        des: "The FatFreq Deuce is a bass lover's dream, with dual dynamic drivers (one for mid-bass, one for sub-bass) tuned for visceral impact. Its compact shells offer comfort, while the 110dB/mW sensitivity ensures loudness even from weak sources. A niche choice for EDM and hip-hop enthusiasts.",
        fr: "  https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-FATfreq_X_HBB-Deuce-graph.png?v=1735634746  ",
        drivers: "2DD (Bass Focused)",
        connectors: "2-pin (Detachable)",
        sensi: "110dB/mW",
        fres: "10Hz – 30kHz",
        impedence: "16Ω",
        thd: "<0.5% (1kHz)",  
        weight: "20g (approx.)",  
        cable: "High-purity copper",  
        inTheBox: "IEMs, cable, ear tips, carrying pouch"  
      },
      {
        id: 17,
        name: "Sennheiser - IE 600",
        price: 74990,
        rating: 4.7,
        image1: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-IE600-01.jpg?v=1654069523&width=1000",
        image: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-IE600-011.jpg?v=1721025160&width=1000",
        category: 'iems',
        img3: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-IE300-04.jpg?v=1721025160&width=1000",
        img4: "https://www.headphonezone.in/cdn/shop/products/Headphone-Zone-Sennheiser-IE600-06.jpg?v=1721025160&width=1000",
        img5: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-IE-600-scrolling-04.jpg?v=1727173522&width=1200",
        bname: "SENNHEISER",
        pname: "IE 600",
        des: "The Sennheiser IE 600 features a 7mm ultra-wideband dynamic driver with an innovative resonator chamber design for precise, distortion-free sound. The housings are 3D-printed from ZR01 amorphous zirconium, making them exceptionally durable yet lightweight. With a frequency response of 4Hz-46.5kHz, the IE 600 delivers exceptional detail retrieval across the entire spectrum.",
        fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-IE-600-graph.png?v=1727164627",
        drivers: "7mm Dynamic Driver",
        connectors: "MMCX (Detachable)",
        sensi: "118dB (1kHz, 1Vrms)",
        fres: "4Hz – 46.5kHz",
        impedence: "18Ω",
        thd: "<0.1% (94dB SPL)",  
        weight: "6g (per earpiece)",  
        cable: "High-purity OFC cable with Fidelity+ MMCX",  
        inTheBox: "IEMs, cable, ear tips (silicone/foam), cleaning tool, carrying case"  
      },
      {
        id: 18,
        name: "Sennheiser - IE 900",
        price: 129990,
        rating: 4.9,
        image1: "https://www.headphonezone.in/cdn/shop/products/4789c8036265954bd92ff4be3c7c650f.jpg?v=1645442871&width=1000",
        image: "https://www.headphonezone.in/cdn/shop/products/677666bd3f65171c645eb8168d22447f.jpg?v=1645442871&width=1000",
        category: 'iems',
        img3: "https://www.headphonezone.in/cdn/shop/products/56b90f2cc19f492d282af58d00dade7b.jpg?v=1706876395&width=1000",
        img4: "https://www.headphonezone.in/cdn/shop/files/Headphone-Zone-Sennheiser-IE-900-Gallery-01.jpg?v=1706876398&width=1000",
        img5: "https://www.headphonezone.in/cdn/shop/products/3f052d05894aff14fe51f23e2b6f0597.jpg?v=1706874482&width=1000",
        bname: "SENNHEISER",
        pname: "IE 900",
        des: "The flagship Sennheiser IE 900 features an ultra-precise 7mm XWB (Extra Wide Band) dynamic driver with triple-chamber absorber system for unparalleled resolution. The milled aluminum housings provide perfect resonance control, while the Fidelity+ MMCX connectors ensure reliable connectivity. With a frequency response of 5Hz-48kHz and Sennheiser's proprietary acoustic vortex technology, the IE 900 sets new standards for single-driver IEM performance.",
        fr: "https://cdn.shopify.com/s/files/1/0153/8863/files/Headphone-Zone-Sennheiser-IE-900-Grph.png?v=1691568243",
        drivers: "7mm XWB Dynamic Driver",
        connectors: "MMCX (Detachable)",
        sensi: "123dB (1kHz, 1Vrms)",
        fres: "5Hz – 48kHz",
        impedence: "16Ω",
        thd: "<0.05% (94dB SPL)",  
        weight: "4g (per earpiece)",  
        cable: "High-end OFC cable with Fidelity+ MMCX",  
        inTheBox: "IEMs, cable, ear tips (silicone/foam), cleaning tool, premium carrying case"  
      }
  ];
  export default Prodata;